name: Deploy to Multiple Vercel Accounts

on:
  push:
    branches: [master]

jobs:
  deploy-your-account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN_VAIBHAV }}
          vercel-org-id: ${{ secrets.ORG_ID_VAIBHAV }}
          vercel-project-id: ${{ secrets.PROJECT_ID_VAIBHAV }}
          vercel-args: '--prod'

  deploy-sudesh-account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN_SUDESH }}
          vercel-org-id: ${{ secrets.ORG_ID_SUDESH }}
          vercel-project-id: ${{ secrets.PROJECT_ID_SUDESH }}
          vercel-args: '--prod'